# Generated by Django 4.2.2 on 2023-06-29 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
